# Generated by Django 3.1 on 2020-12-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('cost', models.CharField(max_length=255)),
                ('delivery_fees', models.CharField(max_length=255)),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
